apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-code-back-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-code-back
  template:
    metadata:
      labels:
        app: mirror-code-back
    spec:
      containers:
        - name: mirror-code-back
          image: myonim/code-mirror-mirror-code-back
          
---
apiVersion: v1
kind: Service
metadata:
  name: mirror-code-back-srv
spec:
  selector:
    app: mirror-code-back
  ports:
    - name: mirror-code-back
      protocol: TCP
      port: 3000
      targetPort: 3000
